import ApolloClassroomProvider from '@/app/providers/ApolloProvider'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Admin Dasboard',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <ApolloClassroomProvider>
        {children}
        </ApolloClassroomProvider>
        </body>
      
    </html>
  )
}
